title: "Tom Waits-løpet 2019 Tracker"
email: kusmabite@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dette er en webapp some lar deg holde oversikt over hvor langt du har
  kommet i Tom Waits Løpet 2019.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kusmabite
github_username: kuusma

markdown: kramdown

exclude:
- Gemfile
- Gemfile.lock
